name: Build

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.0
        with:
          cmdline-tools-version: 10406996

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.4.2
        with:
          ndk-version: "r26b"
          link-to-sdk: true
      - name: Setup Go Mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH=$PATH:~/go/bin

      - name: Build
        run: |
          gomobile init
          go mod tidy
          gomobile bind -ldflags="-w -s" -target=android -androidapi=21 -o=tun2socks.aar ./

        # Upload APK artifact
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tun2socks.aar
          path: |
            ./tun2socks.aar

      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tun2socks.aar
          asset_name: tun2socks.aar
          tag: ${{ github.ref }}
          overwrite: true
